local way = {}
local rs = game:GetService("Replicatedstorage")
local Roact = require(game:GetService("ReplicatedStorage").Roact)
local Settings = require(script.Parent.Parent.Parent.Parent:WaitForChild("Settings"))
local Blip = require(script.Parent.Blip)

local CollectionService = game:GetService("CollectionService")
local Players = game:GetService("Players")

local plr = Players.LocalPlayer
----toto tu definuju bo se bo
local blipContainer = Roact.Component:extend("BlipContainer")

---



return way
